#define WEBDATA_SZ 56474
/*
 * Generated by Ralink WEB converter:Sat Feb  7 01:26:43 AM CST 2026
 * Do not edit
 */
extern void web__images_wifi2_png(http_req *req);
extern void web__js_spec_js(http_req *req);
extern void web__js_wireless_js(http_req *req);
extern void web__images_select_arrow_png(http_req *req);
extern void web__css_setting_css(http_req *req);
extern void web__reboot_html(http_req *req);
extern void web__images_wifi_png(http_req *req);
extern void web__setting_html(http_req *req);
extern void web__images_setSucess_png(http_req *req);
extern void web__images_wifi1_png(http_req *req);
extern void web__count_html(http_req *req);
extern void web__css_index_css(http_req *req);
extern void web__js_utils_adv_js(http_req *req);
extern void web__images_wifi3_png(http_req *req);
extern void web__js_extender_js(http_req *req);
extern void web__index_html(http_req *req);
extern void web__images_WF8300_png(http_req *req);
extern void web__images_lock_png(http_req *req);
extern void web__js_utils_js(http_req *req);
extern void web__extender_html(http_req *req);
extern void web__factorySetting_html(http_req *req);
extern void web__firmware_htm(http_req *req);
extern void web__images_search_png(http_req *req);
extern void web__css_firmware_css(http_req *req);
extern void web__images_arrow_down_png(http_req *req);
extern void web__css_count_css(http_req *req);
extern void web__css_extender_css(http_req *req);
extern void web__images_hengloading_gif(http_req *req);
