/*
 * Generated by Ralink WEB converter:Sat Feb  7 01:26:42 AM CST 2026
 * Do not edit
 */
#include <http_proc.h>
#include "webpage.h"
#include "web_config.h"

time_t time_pages_created =(1770398802+28800);
extern char _binary_webdata_bin_start[];
char *zweb_location = &_binary_webdata_bin_start[0];

webpage_entry webpage_table[]= {
{ "/count.html", web__count_html, 804, WEBP_COMPRESS, (void *)0, NULL, 0 },
{ "/css/count.css", web__css_count_css, 689, WEBP_COMPRESS|NO_AUTH, (void *)0, NULL, 0 },
{ "/css/extender.css", web__css_extender_css, 754, WEBP_COMPRESS|NO_AUTH, (void *)0, NULL, 0 },
{ "/css/firmware.css", web__css_firmware_css, 520, WEBP_COMPRESS|NO_AUTH, (void *)0, NULL, 0 },
{ "/css/index.css", web__css_index_css, 809, WEBP_COMPRESS|NO_AUTH, (void *)0, NULL, 0 },
{ "/css/setting.css", web__css_setting_css, 1083, WEBP_COMPRESS|NO_AUTH, (void *)0, NULL, 0 },
{ "/extender.html", web__extender_html, 2330, WEBP_COMPRESS, (void *)0, NULL, 0 },
{ "/factorySetting.html", web__factorySetting_html, 935, WEBP_COMPRESS, (void *)0, NULL, 0 },
{ "/firmware.htm", web__firmware_htm, 852, WEBP_COMPRESS, (void *)0, NULL, 0 },
{ "/images/arrow_down.png", web__images_arrow_down_png, 849, WEBP_COMPRESS, (void *)0, NULL, 0 },
{ "/images/hengloading.gif", web__images_hengloading_gif, 3817, WEBP_COMPRESS|NO_AUTH|CACHE, (void *)0, NULL, 0 },
{ "/images/lock.png", web__images_lock_png, 729, WEBP_COMPRESS, (void *)0, NULL, 0 },
{ "/images/search.png", web__images_search_png, 1222, WEBP_COMPRESS, (void *)0, NULL, 0 },
{ "/images/select_arrow.png", web__images_select_arrow_png, 834, WEBP_COMPRESS, (void *)0, NULL, 0 },
{ "/images/setSucess.png", web__images_setSucess_png, 3571, WEBP_COMPRESS, (void *)0, NULL, 0 },
{ "/images/WF8300.png", web__images_WF8300_png, 13727, WEBP_COMPRESS, (void *)0, NULL, 0 },
{ "/images/wifi1.png", web__images_wifi1_png, 905, WEBP_COMPRESS, (void *)0, NULL, 0 },
{ "/images/wifi2.png", web__images_wifi2_png, 994, WEBP_COMPRESS, (void *)0, NULL, 0 },
{ "/images/wifi3.png", web__images_wifi3_png, 765, WEBP_COMPRESS, (void *)0, NULL, 0 },
{ "/images/wifi.png", web__images_wifi_png, 3727, WEBP_COMPRESS, (void *)0, NULL, 0 },
{ "/index.html", web__index_html, 541, WEBP_COMPRESS, (void *)0, NULL, 0 },
{ "/js/extender.js", web__js_extender_js, 1329, WEBP_COMPRESS|NO_AUTH, (void *)0, NULL, 0 },
{ "/js/spec.js", web__js_spec_js, 3377, WEBP_COMPRESS|NO_AUTH, (void *)0, NULL, 0 },
{ "/js/utils_adv.js", web__js_utils_adv_js, 3103, WEBP_COMPRESS|NO_AUTH, (void *)0, NULL, 0 },
{ "/js/utils.js", web__js_utils_js, 4591, WEBP_COMPRESS|NO_AUTH, (void *)0, NULL, 0 },
{ "/js/wireless.js", web__js_wireless_js, 684, WEBP_COMPRESS|NO_AUTH, (void *)0, NULL, 0 },
{ "/reboot.html", web__reboot_html, 503, WEBP_COMPRESS, (void *)0, NULL, 0 },
{ "/setting.html", web__setting_html, 2430, WEBP_COMPRESS, (void *)0, NULL, 0 },
{0 , NULL, 0, 0, 0, NULL, 0},
};
