/*
 * Generated by Ralink WEB converter: Sat Feb  7 01:26:43 2026
 * Do not edit
 */

#include <http_proc.h>
#include <cgi_api.h>


void web__images_wifi_png(http_req *req, char *datap)
{
	WEB_write_blk(req, datap, 0, 3751);


}
