/*
 * Generated by Ralink WEB converter: Sat Feb  7 01:26:43 2026
 * Do not edit
 */

#include <http_proc.h>
#include <cgi_api.h>


void web__js_spec_js(http_req *req, char *datap)
{
	WEB_write_blk(req, datap, 0, 252);

 #ifdef APCLI_SUPPORT 

	WEB_write_blk(req, datap, 252, 45);

 #endif //APCLI_SUPPORT 

	WEB_write_blk(req, datap, 297, 199);

 #ifdef CONFIG_PPTP

	WEB_write_blk(req, datap, 496, 43);

 #endif //CONFIG_PPTP

	WEB_write_blk(req, datap, 539, 1);

 #ifdef CONFIG_L2TP

	WEB_write_blk(req, datap, 540, 43);

 #endif //CONFIG_L2TP

	WEB_write_blk(req, datap, 583, 74);

 #ifdef CONFIG_WIRELESS

	WEB_write_blk(req, datap, 657, 46);

 #endif //CONFIG_WIRELESS 

	WEB_write_blk(req, datap, 703, 399);

 #ifdef CONFIG_DDNS

	WEB_write_blk(req, datap, 1102, 39);

 #endif CONFIG_DDNS

	WEB_write_blk(req, datap, 1141, 40);

 #ifdef CONFIG_QOS

	WEB_write_blk(req, datap, 1181, 36);

 #endif CONFIG_QOS

	WEB_write_blk(req, datap, 1217, 1);

 #ifdef CONFIG_WIRELESS

	WEB_write_blk(req, datap, 1218, 319);

 #ifdef WSC_AP_SUPPORT 

	WEB_write_blk(req, datap, 1537, 318);

 #endif //WSC_AP_SUPPORT 

	WEB_write_blk(req, datap, 1855, 1);

 #ifdef APCLI_SUPPORT 

	WEB_write_blk(req, datap, 1856, 97);

 #endif //APCLI_SUPPORT 

	WEB_write_blk(req, datap, 1953, 1);

 #endif //CONFIG_WIRELESS 

	WEB_write_blk(req, datap, 1954, 4230);

 #ifdef CONFIG_PPTP

	WEB_write_blk(req, datap, 6184, 50);

 #endif //CONFIG_PPTP

	WEB_write_blk(req, datap, 6234, 1);

 #ifdef CONFIG_L2TP

	WEB_write_blk(req, datap, 6235, 50);

 #endif //CONFIG_L2TP

	WEB_write_blk(req, datap, 6285, 750);

 #ifdef CONFIG_PPTP

	WEB_write_blk(req, datap, 7035, 130);

 #endif //CONFIG_PPTP

	WEB_write_blk(req, datap, 7165, 1);

 #ifdef CONFIG_L2TP

	WEB_write_blk(req, datap, 7166, 130);

 #endif //CONFIG_L2TP

	WEB_write_blk(req, datap, 7296, 2347);


}
