/*
 * Generated by Ralink WEB converter: Sat Feb  7 01:26:42 2026
 * Do not edit
 */

#include <http_proc.h>
#include <cgi_api.h>


void web__firmware_htm(http_req *req, char *datap)
{
	WEB_write_blk(req, datap, 0, 465);

CGI_CUST_VER_STR();

	WEB_write_blk(req, datap, 465, 28);

CGI_FMW_BUILD_SEC();

	WEB_write_blk(req, datap, 493, 5);


CGI_MAP(opmode, CFG_SYS_OPMODE);


	WEB_write_blk(req, datap, 498, 999);


}
