/*
 * Generated by Ralink WEB converter: Sat Feb  7 01:26:43 2026
 * Do not edit
 */

#include <http_proc.h>
#include <cgi_api.h>


void web__setting_html(http_req *req, char *datap)
{
	WEB_write_blk(req, datap, 0, 661);

 CGI_GET_SCAN_RESULT();

	WEB_write_blk(req, datap, 661, 1352);


CGI_MAP(WirelessMode2, CFG_WLN_WirelessMode);
CGI_MAP(n_bandwidth, CFG_WLN_HT_BW);
CGI_MAP(BasicRate2, CFG_WLN_BasicRate);
CGI_MAP(ssid, CFG_WLN_SSID1);
CGI_MAP(bssid_num, CFG_WLN_BssidNum);
CGI_MAP(AutoChannelSelect2, CFG_WLN_AutoChannelSelect);
CGI_MAP(sz11gChannel, CFG_WLN_Channel);
CGI_MAP(EncrypType2, CFG_WLN_WdsEncrypType);
CGI_MAP(WdsDefaultKey2, CFG_WLN_WdsDefaultKeyID);
CGI_MAP(EXTCHA2, CFG_WLN_HT_EXTCHA);
CGI_MAP(opmode, CFG_SYS_OPMODE);

CGI_MAP(apcli_ssid, CFG_WLN_ApCliSsid);
CGI_MAP(apcli_bssid, CFG_WLN_ApCliBssid);
CGI_MAP(apcli_enable, CFG_WLN_ApCliEnable);
CGI_MAP(apcli_passphrase, CFG_WLN_ApCliWPAPSK);
CGI_MAP(apcliencryptype2, CFG_WLN_ApCliEncrypType);
CGI_MAP(apcliauth2, CFG_WLN_ApCliAuthMode);
CGI_MAP(ApCliDefaultKeyID2, CFG_WLN_ApCliDefaultKeyID);

CGI_MAP(SSIDIndexTemp, CFG_WLN_SSIDIndex);
CGI_MAP(WscAuthType2, CFG_WLN_WscAuthType);
CGI_MAP(WscEncrypType2, CFG_WLN_WscEncrypType);
CGI_MAP(WscConfigured2, CFG_WLN_WscConfStatus);
CGI_MAP(WscNewKey2, CFG_WLN_WscNewKey);
CGI_MAP(SecurityMode2, CFG_WLN_SecurityMode);
CGI_MAP(AuthMode, CFG_WLN_AuthMode);
CGI_MAP(EncrypType, CFG_WLN_EncrypType);
CGI_MAP(WPAPSK1Temp, CFG_WLN_WPAPSK1);
CGI_MAP(WPAPSK2Temp, CFG_WLN_WPAPSK2);
CGI_MAP(WPAPSK3Temp, CFG_WLN_WPAPSK3);
CGI_MAP(WPAPSK4Temp, CFG_WLN_WPAPSK4);

CGI_MAP(dns, CFG_DNS_EN);


	WEB_write_blk(req, datap, 2013, 4992);


}
