/*
 * Generated by Ralink WEB converter: Sat Feb  7 01:26:42 2026
 * Do not edit
 */

#include <http_proc.h>
#include <cgi_api.h>


void web__css_extender_css(http_req *req, char *datap)
{
	WEB_write_blk(req, datap, 0, 2525);


}
